import React from "react";

const Features = () => {
  return (
    <div
      className={" bg-primary text-center flex flex-col justify-center py-12"}
    >
      <h3 className="lg:text-4xl sm:text-3xl text-2xl font-bold lg:leading-[50px] sm:leading-[50px] leading-8 lg:w-[85%] mx-auto mb-2 md:mb-5">
        Features in the ecommerce system
      </h3>

      {/* VStack */}
      <div className="flex flex-col gap-3 lg:w-5/12 mx-auto">
        {/* Services */}
        <ServiceItem
          title={"a. Content management for Learning Materials"}
          body={
            <p>
              - Capability to handle content in multiple languages.
              <br />
              - Ability to handle various types of content (e.g. text, audio,
              images)
              <br />
              - Facilitation of content generated by users.
              <br />
              - Organized storage of educational materials.
              <br />
              - Tools for creating courses.
              <br />
              - Search functionality for learning content by titles, metadata,
              and full-text.
              <br />
            </p>
          }
        />
        <ServiceItem
          title={"b. Delivery of educational content"}
          body={
            <p>
              - Accessibility across multiple devices for learners, trainers,
              and managers.
              <br />
              - Self-enrollment for learners through online admission forms.
              <br />
              - Learner profiles containing contact information, course details,
              exam results, certificates, and more.
              <br />
              - Personalized learning paths driven by AI.
              <br />
              - Online assignments for learners.
              <br />
              - Evaluation of learner performance through tests, quizzes, and
              exams.
              <br />
              - Management of digital certificates upon completion of courses.
              <br />
            </p>
          }
        />
        <ServiceItem
          title={"c. Data analysis and reporting"}
          body={
            <p>
              - Advice and suggestions for learners based on AI.
              <br />
              - Tracking of learning history and progress.
              <br />
              - Collection of feedback from learners.
              <br />
              - Dashboards for trainers and managers displaying usage of
              learning content, portal usage, time spent on courses, learners’
              performance, and satisfaction, among other things.
              <br />
            </p>
          }
        />

        <ServiceItem
          title={"d. Interaction and collaborative learning"}
          body={
            <p>
              - Online discussion boards. <br />
              - Instant messaging. <br />
              - Online forums. <br />
              - Collaborative learning groups. <br />
              - Interaction with e-learning content through likes, shares, and
              comments. <br />
            </p>
          }
        />
        <ServiceItem
          title={"e. Security"}
          body={
            <p>
              - Access to training materials and records of competence based on
              roles (e.g. courses, assignments, exams, attendance, grades,
              certifications).
              <br />
              - Backing up of records and progress of learners.
              <br />
            </p>
          }
        />
      </div>
    </div>
  );
};

export default Features;
const ServiceItem = ({ title, body }) => (
  <div className="text-center ">
    {/* // title */}
    <h6 className="font-bold text-lg">{title}</h6>

    {/* // body */}
    <p className="leading-8 text-base sm:text-lg px-2">{body}</p>
  </div>
);
